In [2]:
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None

# Dataset 1: Divvy Bike Data

In [3]:
# Read the various csv files from Nov 2019 to Oct 2020 (includes Oct 2019 as well)
d1 = pd.read_csv("Divvy_Trips_2019_Q4.csv")
d2 = pd.read_csv("divvydata_Jan-Mar2020.csv")
d3 = pd.read_csv("202004-divvy-tripdata.csv")
d4 = pd.read_csv("202005-divvy-tripdata.csv")
d5 = pd.read_csv("202006-divvy-tripdata.csv")
d6 = pd.read_csv("202007-divvy-tripdata.csv")
d7 = pd.read_csv("202008-divvy-tripdata.csv")
d8 = pd.read_csv("202009-divvy-tripdata.csv")
d9 = pd.read_csv("202010-divvy-tripdata.csv")

In [4]:
# d1 (2019 Quarter data) has some columns with differin names; renaming to match the other data
d1.rename({'start_station_nam': 'start_station_name'}, inplace=True, axis=1)
d1 = d1[['ride_id', 'started_at', 'ended_at', 'start_station_name', 'start_station_id', 'end_station_name', 'end_station_id', 'member_casual']]
d1.head()

,ride_id,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual
0,25223640,10/1/2019 0:01,10/1/2019 0:17,Sheffield Ave & Kingsbury St,20,Leavitt St & Armitage Ave,309,member
1,25223641,10/1/2019 0:02,10/1/2019 0:06,Throop (Loomis) St & Taylor St,19,Morgan St & Polk St,241,member
2,25223642,10/1/2019 0:04,10/1/2019 0:18,Milwaukee Ave & Grand Ave,84,Wabash Ave & Grand Ave,199,member
3,25223643,10/1/2019 0:04,10/1/2019 0:43,Lakeview Ave & Fullerton Pkwy,313,Kedzie Ave & Palmer Ct,290,member
4,25223644,10/1/2019 0:04,10/1/2019 0:35,Ashland Ave & Division St,210,Western Ave & Congress Pkwy,382,member

In [5]:
# merge all the datasets for the months to get the total data for the Divvy bikes
divvy_data = pd.concat([d1, d2, d3, d4, d5, d6, d7, d8, d9])
divvy_data

,ride_id,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual
0,25223640,10/1/2019 0:01,10/1/2019 0:17,Sheffield Ave & Kingsbury St,20.0,Leavitt St & Armitage Ave,309.0,member
1,25223641,10/1/2019 0:02,10/1/2019 0:06,Throop (Loomis) St & Taylor St,19.0,Morgan St & Polk St,241.0,member
2,25223642,10/1/2019 0:04,10/1/2019 0:18,Milwaukee Ave & Grand Ave,84.0,Wabash Ave & Grand Ave,199.0,member
3,25223643,10/1/2019 0:04,10/1/2019 0:43,Lakeview Ave & Fullerton Pkwy,313.0,Kedzie Ave & Palmer Ct,290.0,member
4,25223644,10/1/2019 0:04,10/1/2019 0:35,Ashland Ave & Division St,210.0,Western Ave & Congress Pkwy,382.0,member
...,...,...,...,...,...,...,...,...
388648,73F13E3E24954C57,10/28/2020 8:31,10/28/2020 8:37,Leavitt St & Division St,658.0,Wood St & Augusta Blvd,657.0,member
388649,6F68E6F5704E2C08,10/6/2020 10:04,10/6/2020 10:13,Aberdeen St & Jackson Blvd,21.0,Loomis St & Lexington St,320.0,member
388650,79C12697BEBF5B0A,10/15/2020 6:54,10/15/2020 7:22,California Ave & Altgeld St,502.0,California Ave & Altgeld St,502.0,casual
388651,907E10168C2F53FE,10/16/2020 10:29,10/16/2020 10:50,Lincoln Ave & Diversey Pkwy,152.0,Ashland Ave & Blackhawk St,333.0,casual
388652,A12644A5B2CA6B4E,10/31/2020 20:13,10/31/2020 20:24,Clark St & Newport St,632.0,Clark St & Winnemac Ave,325.0,casual

# Dataset 2 - Weather Data

In [6]:
# read the weather data from the csv file into a pandas dataframe
weather = pd.read_csv("weather.csv")
weather

,Date,d,Time,Temperature,Humidity,Wind Speed,Wind Gust,Precipitation,Condition
0,11/1/2019 23:53,11/1/2019,23:53,27 F,81,7 mph,0 mph,0.0 in,Fair
1,11/1/2019 0:53,11/1/2019,0:53,26 F,81,8 mph,0 mph,0.0 in,Fair
2,11/1/2019 1:53,11/1/2019,1:53,25 F,85,8 mph,0 mph,0.0 in,Fair
3,11/1/2019 2:53,11/1/2019,2:53,26 F,84,6 mph,0 mph,0.0 in,Fair
4,11/1/2019 3:53,11/1/2019,3:53,25 F,88,5 mph,0 mph,0.0 in,Fair
...,...,...,...,...,...,...,...,...,...
10331,10/31/2020 18:53,10/31/2020,18:53,55 F,51,15mph,30mph,0.0in,Partly Cloudy
10332,10/31/2020 19:53,10/31/2020,19:53,54 F,55,18mph,29mph,0.0in,Mostly Cloudy
10333,10/31/2020 20:53,10/31/2020,20:53,54 F,55,18mph,29mph,0.0in,Cloudy
10334,10/31/2020 21:53,10/31/2020,21:53,52 F,66,16mph,30mph,0.0in,Cloudy
10335,10/31/2020 22:53,10/31/2020,22:53,53 F,61,16mph,25mph,0.0in,Mostly Cloudy

In [7]:
weather = weather[['Date', 'Temperature', 'Humidity', 'Wind Speed', 'Wind Gust', 'Precipitation', 'Condition']]
weather.head()

,Date,Temperature,Humidity,Wind Speed,Wind Gust,Precipitation,Condition
0,11/1/2019 23:53,27 F,81,7 mph,0 mph,0.0 in,Fair
1,11/1/2019 0:53,26 F,81,8 mph,0 mph,0.0 in,Fair
2,11/1/2019 1:53,25 F,85,8 mph,0 mph,0.0 in,Fair
3,11/1/2019 2:53,26 F,84,6 mph,0 mph,0.0 in,Fair
4,11/1/2019 3:53,25 F,88,5 mph,0 mph,0.0 in,Fair

In [8]:
# Convert the date columns in the divvy data to datetime format 
divvy_data['started_at'] = pd.to_datetime(divvy_data.started_at)
divvy_data['ended_at'] = pd.to_datetime(divvy_data.ended_at)
divvy_data['Year'] = divvy_data.started_at.dt.year
divvy_data['Month'] = divvy_data.started_at.dt.month
divvy_data['Day'] = divvy_data.started_at.dt.day
divvy_data['Hour'] = divvy_data.started_at.dt.hour

# save the dataframe to a csv
divvy_data.to_csv("divvy_final.csv", index=False)
divvy_data

,ride_id,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual,Year,Month,Day,Hour
0,25223640,2019-10-01 00:01:00,2019-10-01 00:17:00,Sheffield Ave & Kingsbury St,20.0,Leavitt St & Armitage Ave,309.0,member,2019,10,1,0
1,25223641,2019-10-01 00:02:00,2019-10-01 00:06:00,Throop (Loomis) St & Taylor St,19.0,Morgan St & Polk St,241.0,member,2019,10,1,0
2,25223642,2019-10-01 00:04:00,2019-10-01 00:18:00,Milwaukee Ave & Grand Ave,84.0,Wabash Ave & Grand Ave,199.0,member,2019,10,1,0
3,25223643,2019-10-01 00:04:00,2019-10-01 00:43:00,Lakeview Ave & Fullerton Pkwy,313.0,Kedzie Ave & Palmer Ct,290.0,member,2019,10,1,0
4,25223644,2019-10-01 00:04:00,2019-10-01 00:35:00,Ashland Ave & Division St,210.0,Western Ave & Congress Pkwy,382.0,member,2019,10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
388648,73F13E3E24954C57,2020-10-28 08:31:00,2020-10-28 08:37:00,Leavitt St & Division St,658.0,Wood St & Augusta Blvd,657.0,member,2020,10,28,8
388649,6F68E6F5704E2C08,2020-10-06 10:04:00,2020-10-06 10:13:00,Aberdeen St & Jackson Blvd,21.0,Loomis St & Lexington St,320.0,member,2020,10,6,10
388650,79C12697BEBF5B0A,2020-10-15 06:54:00,2020-10-15 07:22:00,California Ave & Altgeld St,502.0,California Ave & Altgeld St,502.0,casual,2020,10,15,6
388651,907E10168C2F53FE,2020-10-16 10:29:00,2020-10-16 10:50:00,Lincoln Ave & Diversey Pkwy,152.0,Ashland Ave & Blackhawk St,333.0,casual,2020,10,16,10
388652,A12644A5B2CA6B4E,2020-10-31 20:13:00,2020-10-31 20:24:00,Clark St & Newport St,632.0,Clark St & Winnemac Ave,325.0,casual,2020,10,31,20

In [9]:
# convert the weather date to datetime format
weather['Date'] = pd.to_datetime(weather.Date)
weather['Year'] = weather.Date.dt.year
weather['Month'] = weather.Date.dt.month
weather['Day'] = weather.Date.dt.day
weather['Hour'] = weather.Date.dt.hour

# save the dataframe to a csv file
weather.to_csv("weather_final.csv", index=False)
weather

,Date,Temperature,Humidity,Wind Speed,Wind Gust,Precipitation,Condition,Year,Month,Day,Hour
0,2019-11-01 23:53:00,27 F,81,7 mph,0 mph,0.0 in,Fair,2019,11,1,23
1,2019-11-01 00:53:00,26 F,81,8 mph,0 mph,0.0 in,Fair,2019,11,1,0
2,2019-11-01 01:53:00,25 F,85,8 mph,0 mph,0.0 in,Fair,2019,11,1,1
3,2019-11-01 02:53:00,26 F,84,6 mph,0 mph,0.0 in,Fair,2019,11,1,2
4,2019-11-01 03:53:00,25 F,88,5 mph,0 mph,0.0 in,Fair,2019,11,1,3
...,...,...,...,...,...,...,...,...,...,...,...
10331,2020-10-31 18:53:00,55 F,51,15mph,30mph,0.0in,Partly Cloudy,2020,10,31,18
10332,2020-10-31 19:53:00,54 F,55,18mph,29mph,0.0in,Mostly Cloudy,2020,10,31,19
10333,2020-10-31 20:53:00,54 F,55,18mph,29mph,0.0in,Cloudy,2020,10,31,20
10334,2020-10-31 21:53:00,52 F,66,16mph,30mph,0.0in,Cloudy,2020,10,31,21
10335,2020-10-31 22:53:00,53 F,61,16mph,25mph,0.0in,Mostly Cloudy,2020,10,31,22

In [10]:
# merge both the divvy and weather data based on the extracted year, month, day and hour
merged_df = divvy_data.merge(weather, how='inner', on=['Year', 'Month', 'Day', 'Hour'])
merged_df.drop(['Date'], axis=1, inplace=True)
merged_df

,ride_id,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual,Year,Month,Day,Hour,Temperature,Humidity,Wind Speed,Wind Gust,Precipitation,Condition
0,25612325,2019-11-01 00:00:00,2019-11-01 00:08:00,Ellis Ave & 55th St,420.0,Harper Ave & 59th St,425.0,member,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair
1,25612326,2019-11-01 00:01:00,2019-11-01 00:30:00,Western Ave & Winnebago Ave,116.0,Morgan St & Polk St,241.0,casual,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair
2,25612327,2019-11-01 00:01:00,2019-11-01 00:38:00,Western Ave & Winnebago Ave,116.0,May St & Taylor St,22.0,member,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair
3,25612328,2019-11-01 00:02:00,2019-11-01 00:09:00,Lincoln Ave & Winona St,472.0,Maplewood Ave & Peterson Ave,455.0,member,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair
4,25612329,2019-11-01 00:02:00,2019-11-01 00:04:00,Clinton St & Madison St,77.0,Clinton St & Washington Blvd,91.0,member,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3803530,7BBA6E8E6E19BA46,2020-10-22 05:17:00,2020-10-22 05:21:00,NaN,NaN,NaN,NaN,member,2020,10,22,5,49 F,90,16mph,0mph,0.0in,Light Rain
3803531,5DE9694204DED47B,2020-10-22 05:16:00,2020-10-22 05:17:00,NaN,NaN,NaN,NaN,member,2020,10,22,5,48 F,93,9mph,22mph,0.0in,Light Drizzle
3803532,5DE9694204DED47B,2020-10-22 05:16:00,2020-10-22 05:17:00,NaN,NaN,NaN,NaN,member,2020,10,22,5,48 F,93,13mph,0mph,0.0in,Light Rain
3803533,5DE9694204DED47B,2020-10-22 05:16:00,2020-10-22 05:17:00,NaN,NaN,NaN,NaN,member,2020,10,22,5,48 F,93,16mph,0mph,0.0in,Light Rain
3803534,5DE9694204DED47B,2020-10-22 05:16:00,2020-10-22 05:17:00,NaN,NaN,NaN,NaN,member,2020,10,22,5,49 F,90,16mph,0mph,0.0in,Light Rain

# Dataset 3: Holidays

In [40]:
hols = pd.read_csv('holidays.csv')
hols

           Date Holiday_Name
0    2019-11-01  Not Holiday
1    2019-11-02  Not Holiday
2    2019-11-03  Not Holiday
3    2019-11-04  Not Holiday
4    2019-11-05  Not Holiday
..          ...          ...
393  2020-11-26  Not Holiday
394  2020-11-27  Not Holiday
395  2020-11-28  Not Holiday
396  2020-11-29  Not Holiday
397  2020-11-30  Not Holiday

[398 rows x 2 columns]

In [43]:
hols.Date = pd.to_datetime(hols.Date)
hols['Year'] = hols.Date.dt.year
hols['Month'] = hols.Date.dt.month
hols['Day'] = hols.Date.dt.day
hols

          Date Holiday_Name  Year  Month  Day
0   2019-11-01  Not Holiday  2019     11    1
1   2019-11-02  Not Holiday  2019     11    2
2   2019-11-03  Not Holiday  2019     11    3
3   2019-11-04  Not Holiday  2019     11    4
4   2019-11-05  Not Holiday  2019     11    5
..         ...          ...   ...    ...  ...
393 2020-11-26  Not Holiday  2020     11   26
394 2020-11-27  Not Holiday  2020     11   27
395 2020-11-28  Not Holiday  2020     11   28
396 2020-11-29  Not Holiday  2020     11   29
397 2020-11-30  Not Holiday  2020     11   30

[398 rows x 5 columns]

In [56]:
final_merged_data = merged_df.merge(hols, how='inner', on=['Year', 'Month', 'Day'])
final_merged_data.drop("Date", axis=1, inplace=True)
final_merged_data

,ride_id,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual,Year,Month,Day,Hour,Temperature,Humidity,Wind Speed,Wind Gust,Precipitation,Condition,Holiday_Name
0,25612325,2019-11-01 00:00:00,2019-11-01 00:08:00,Ellis Ave & 55th St,420.0,Harper Ave & 59th St,425.0,member,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair,Not Holiday
1,25612326,2019-11-01 00:01:00,2019-11-01 00:30:00,Western Ave & Winnebago Ave,116.0,Morgan St & Polk St,241.0,casual,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair,Not Holiday
2,25612327,2019-11-01 00:01:00,2019-11-01 00:38:00,Western Ave & Winnebago Ave,116.0,May St & Taylor St,22.0,member,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair,Not Holiday
3,25612328,2019-11-01 00:02:00,2019-11-01 00:09:00,Lincoln Ave & Winona St,472.0,Maplewood Ave & Peterson Ave,455.0,member,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair,Not Holiday
4,25612329,2019-11-01 00:02:00,2019-11-01 00:04:00,Clinton St & Madison St,77.0,Clinton St & Washington Blvd,91.0,member,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair,Not Holiday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3826984,A4D50CAC9CCFB180,2020-10-20 01:51:00,2020-10-20 01:59:00,Kimbark Ave & 53rd St,322.0,Blackstone Ave & Hyde Park Blvd,121.0,member,2020,10,20,1,44 F,79,9mph,0mph,0.0in,Cloudy,Not Holiday
3826985,2D551117FD01DCE1,2020-10-20 01:04:00,2020-10-20 01:19:00,Pine Grove Ave & Irving Park Rd,254.0,Glenwood Ave & Morse Ave,447.0,member,2020,10,20,1,44 F,79,8mph,0mph,0.0in,Cloudy,Not Holiday
3826986,2D551117FD01DCE1,2020-10-20 01:04:00,2020-10-20 01:19:00,Pine Grove Ave & Irving Park Rd,254.0,Glenwood Ave & Morse Ave,447.0,member,2020,10,20,1,44 F,79,9mph,0mph,0.0in,Cloudy,Not Holiday
3826987,09264F6A1F8E4CEE,2020-10-20 01:38:00,2020-10-20 01:48:00,St. Clair St & Erie St,211.0,Clark St & Armitage Ave,94.0,member,2020,10,20,1,44 F,79,8mph,0mph,0.0in,Cloudy,Not Holiday
3826988,09264F6A1F8E4CEE,2020-10-20 01:38:00,2020-10-20 01:48:00,St. Clair St & Erie St,211.0,Clark St & Armitage Ave,94.0,member,2020,10,20,1,44 F,79,9mph,0mph,0.0in,Cloudy,Not Holiday

In [57]:
final_merged_data.to_csv("final_merged_data.csv", index=False)

In [58]:
final_merged_data.loc[(final_merged_data['Month'] == 12) & (final_merged_data['Day'] == 25)]

,ride_id,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual,Year,Month,Day,Hour,Temperature,Humidity,Wind Speed,Wind Gust,Precipitation,Condition,Holiday_Name
348282,25937355,2019-12-25 00:00:00,2019-12-25 00:13:00,State St & Randolph St,44.0,Indiana Ave & Roosevelt Rd,255.0,member,2019,12,25,0,44 F,82,7 mph,0 mph,0.0 in,Mostly Cloudy,Christmas
348283,25937356,2019-12-25 00:09:00,2019-12-25 00:18:00,Southport Ave & Waveland Ave,227.0,Damen Ave & Melrose Ave,228.0,casual,2019,12,25,0,44 F,82,7 mph,0 mph,0.0 in,Mostly Cloudy,Christmas
348284,25937357,2019-12-25 00:08:00,2019-12-25 00:18:00,Southport Ave & Waveland Ave,227.0,Damen Ave & Melrose Ave,228.0,casual,2019,12,25,0,44 F,82,7 mph,0 mph,0.0 in,Mostly Cloudy,Christmas
348285,25937358,2019-12-25 00:09:00,2019-12-25 00:18:00,Southport Ave & Waveland Ave,227.0,Damen Ave & Melrose Ave,228.0,casual,2019,12,25,0,44 F,82,7 mph,0 mph,0.0 in,Mostly Cloudy,Christmas
348286,25937359,2019-12-25 00:13:00,2019-12-25 00:16:00,Millennium Park,90.0,Michigan Ave & Lake St,52.0,member,2019,12,25,0,44 F,82,7 mph,0 mph,0.0 in,Mostly Cloudy,Christmas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350697,25939919,2019-12-25 23:53:00,2019-12-26 00:18:00,Michigan Ave & 8th St,623.0,Michigan Ave & Lake St,52.0,casual,2019,12,25,23,55 F,77,14 mph,0 mph,0.0 in,Cloudy,Christmas
350698,25939920,2019-12-25 23:53:00,2019-12-25 23:59:00,Canal St & Adams St,192.0,Orleans St & Merchandise Mart Plaza,100.0,member,2019,12,25,23,55 F,77,14 mph,0 mph,0.0 in,Cloudy,Christmas
350699,25939921,2019-12-25 23:58:00,2019-12-26 00:01:00,Dearborn Pkwy & Delaware Pl,140.0,Clark St & Elm St,176.0,member,2019,12,25,23,55 F,77,14 mph,0 mph,0.0 in,Cloudy,Christmas
350700,25939922,2019-12-25 23:59:00,2019-12-26 01:16:00,State St & Pearson St,106.0,Orleans St & Chestnut St (NEXT Apts),620.0,member,2019,12,25,23,55 F,77,14 mph,0 mph,0.0 in,Cloudy,Christmas
350701,25939923,2019-12-25 23:59:00,2019-12-26 00:06:00,Damen Ave & Cortland St,219.0,Ashland Ave & Blackhawk St,333.0,member,2019,12,25,23,55 F,77,14 mph,0 mph,0.0 in,Cloudy,Christmas

# Data Cleaning

In [59]:
final_merged_data.shape

(3826989, 19)

In [60]:
# count number of duplicate rows and missing values in ddataframe
print("Number of duplicate rows: ", len(final_merged_data) - len(final_merged_data.drop_duplicates(subset='ride_id', keep='first')))
print("Number of rows with missing values: ", len(final_merged_data) - len(final_merged_data.dropna()))

Number of duplicate rows:  345513
Number of rows with missing values:  106525

In [61]:
final_merged_data.drop_duplicates(subset='ride_id', keep='first', inplace=True)
final_merged_data

,ride_id,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual,Year,Month,Day,Hour,Temperature,Humidity,Wind Speed,Wind Gust,Precipitation,Condition,Holiday_Name
0,25612325,2019-11-01 00:00:00,2019-11-01 00:08:00,Ellis Ave & 55th St,420.0,Harper Ave & 59th St,425.0,member,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair,Not Holiday
1,25612326,2019-11-01 00:01:00,2019-11-01 00:30:00,Western Ave & Winnebago Ave,116.0,Morgan St & Polk St,241.0,casual,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair,Not Holiday
2,25612327,2019-11-01 00:01:00,2019-11-01 00:38:00,Western Ave & Winnebago Ave,116.0,May St & Taylor St,22.0,member,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair,Not Holiday
3,25612328,2019-11-01 00:02:00,2019-11-01 00:09:00,Lincoln Ave & Winona St,472.0,Maplewood Ave & Peterson Ave,455.0,member,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair,Not Holiday
4,25612329,2019-11-01 00:02:00,2019-11-01 00:04:00,Clinton St & Madison St,77.0,Clinton St & Washington Blvd,91.0,member,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair,Not Holiday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3826979,23638F49B7E7D116,2020-10-20 01:23:00,2020-10-20 01:39:00,Racine Ave & 35th St,367.0,Racine Ave & 18th St,15.0,member,2020,10,20,1,44 F,79,8mph,0mph,0.0in,Cloudy,Not Holiday
3826981,3048BAC5F769B4DD,2020-10-20 01:20:00,2020-10-20 01:36:00,Wells St & Evergreen Ave,291.0,Wabash Ave & Roosevelt Rd,59.0,member,2020,10,20,1,44 F,79,8mph,0mph,0.0in,Cloudy,Not Holiday
3826983,A4D50CAC9CCFB180,2020-10-20 01:51:00,2020-10-20 01:59:00,Kimbark Ave & 53rd St,322.0,Blackstone Ave & Hyde Park Blvd,121.0,member,2020,10,20,1,44 F,79,8mph,0mph,0.0in,Cloudy,Not Holiday
3826985,2D551117FD01DCE1,2020-10-20 01:04:00,2020-10-20 01:19:00,Pine Grove Ave & Irving Park Rd,254.0,Glenwood Ave & Morse Ave,447.0,member,2020,10,20,1,44 F,79,8mph,0mph,0.0in,Cloudy,Not Holiday
3826987,09264F6A1F8E4CEE,2020-10-20 01:38:00,2020-10-20 01:48:00,St. Clair St & Erie St,211.0,Clark St & Armitage Ave,94.0,member,2020,10,20,1,44 F,79,8mph,0mph,0.0in,Cloudy,Not Holiday

In [62]:
final_merged_data.dropna(inplace=True)
final_merged_data

,ride_id,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual,Year,Month,Day,Hour,Temperature,Humidity,Wind Speed,Wind Gust,Precipitation,Condition,Holiday_Name
0,25612325,2019-11-01 00:00:00,2019-11-01 00:08:00,Ellis Ave & 55th St,420.0,Harper Ave & 59th St,425.0,member,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair,Not Holiday
1,25612326,2019-11-01 00:01:00,2019-11-01 00:30:00,Western Ave & Winnebago Ave,116.0,Morgan St & Polk St,241.0,casual,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair,Not Holiday
2,25612327,2019-11-01 00:01:00,2019-11-01 00:38:00,Western Ave & Winnebago Ave,116.0,May St & Taylor St,22.0,member,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair,Not Holiday
3,25612328,2019-11-01 00:02:00,2019-11-01 00:09:00,Lincoln Ave & Winona St,472.0,Maplewood Ave & Peterson Ave,455.0,member,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair,Not Holiday
4,25612329,2019-11-01 00:02:00,2019-11-01 00:04:00,Clinton St & Madison St,77.0,Clinton St & Washington Blvd,91.0,member,2019,11,1,0,26 F,81,8 mph,0 mph,0.0 in,Fair,Not Holiday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3826979,23638F49B7E7D116,2020-10-20 01:23:00,2020-10-20 01:39:00,Racine Ave & 35th St,367.0,Racine Ave & 18th St,15.0,member,2020,10,20,1,44 F,79,8mph,0mph,0.0in,Cloudy,Not Holiday
3826981,3048BAC5F769B4DD,2020-10-20 01:20:00,2020-10-20 01:36:00,Wells St & Evergreen Ave,291.0,Wabash Ave & Roosevelt Rd,59.0,member,2020,10,20,1,44 F,79,8mph,0mph,0.0in,Cloudy,Not Holiday
3826983,A4D50CAC9CCFB180,2020-10-20 01:51:00,2020-10-20 01:59:00,Kimbark Ave & 53rd St,322.0,Blackstone Ave & Hyde Park Blvd,121.0,member,2020,10,20,1,44 F,79,8mph,0mph,0.0in,Cloudy,Not Holiday
3826985,2D551117FD01DCE1,2020-10-20 01:04:00,2020-10-20 01:19:00,Pine Grove Ave & Irving Park Rd,254.0,Glenwood Ave & Morse Ave,447.0,member,2020,10,20,1,44 F,79,8mph,0mph,0.0in,Cloudy,Not Holiday
3826987,09264F6A1F8E4CEE,2020-10-20 01:38:00,2020-10-20 01:48:00,St. Clair St & Erie St,211.0,Clark St & Armitage Ave,94.0,member,2020,10,20,1,44 F,79,8mph,0mph,0.0in,Cloudy,Not Holiday

In [63]:
final_merged_data.shape

(3383787, 19)

In [65]:
final_merged_data.to_csv('cleaned_data.csv', index=False)